const rules = {
  "⚙️ Regulasi Sepeda": [
    "Sepeda yang digunakan adalah sepeda pushbike/balance bike dengan ukuran roda 12 inch",
    "Panjang handlebar maksimal 48 cm dan wajib menggunakan bar end karet/plastik",
    "Wajib menggunakan stem protector demi keamanan rider",
    "Dilarang menambah rem dan lampu yang dapat mengganggu jalannya perlombaan dan membahayakan peserta lainnya",
  ],
  "🧒 Regulasi Riders": [
    "Race berdasarkan tahun lahir sesuai gender (2023: kategori mix)",
    "Wajib menggunakan helm dengan tali dikaitkan. Pelanggaran: penalty poin +3",
    "Wajib memakai sepatu dan kaos kaki saat start. Pelanggaran: +3 poin",
    "Dilarang menggunakan ornamen lampu di helm, sepatu, atau jersey. Pelanggaran: +3 poin",
    "Disarankan menggunakan sarung tangan, knee dan elbow protector",
    "Wajib memakai number plate saat registrasi. Jika tidak: DNS (Did Not Start)",
    "Harus sesuai kelas umur atau naik kelas, dilarang turun kelas atau manipulasi data umur. Pelanggaran: diskualifikasi permanen dari seluruh event",
  ],
  "👨‍👩‍👧 Regulasi Wali Riders": [
    "Wali tidak boleh masuk area track/area steril kecuali atas izin Race Director. Pelanggaran: +8 poin",
    "Harus berjarak minimal 1,5 m dari rider saat start, dilarang menyentuh. Pelanggaran: +3 poin",
    "Dilarang masuk area finish. Pelanggaran: +8 poin",
    "Hanya 1 wali atau pelatih yang diperkenankan bantu di waiting zone (kecuali kategori 2020 – FFA: dilarang masuk)",
    "Dilarang menggunakan alat komunikasi/properti pengganggu konsentrasi. Pelanggaran: +8 poin",
    "Dilarang merokok (termasuk vape) di luar area merokok. Pelanggaran: diskualifikasi",
    "Wali wajib menjaga etika dan kebersihan. Pelanggaran: diskualifikasi",
  ],
  "🏁 Regulasi Perlombaan": [
    "Dilarang menambah alat perekam di sepeda/helm/tubuh rider",
    "Dokumentasi pribadi hanya di luar track",
    "Race memakai 8 line gate start",
    "Perhitungan poin sistem poin terendah: P1 = 1 poin, P2 = 2 poin, dst",
    "Kelas 1 grup: main 3x moto → juara berdasarkan kalkulasi poin (jika sama, lihat finish moto terakhir)",
    "Kelas 2 grup: main 2x moto: P1–P4 → Final Grand Champion, P5–P8 → Final Champion",
  ],
  "🔢 Grup 3–8 dan Perhitungan Klasemen": [
    "Grup 3–8 memiliki sistem lebih kompleks dengan babak Semifinal, Final Champion, Final Pro, Final Novice, Final Rookie, Final Beginner, Final Amateur, Final Newbie, Quarter Final, dan Kualifikasi",
    "Detail sistem klasifikasi dan pembagian grup sudah ditentukan berdasarkan posisi finish masing-masing moto",
  ],
  "🏆 Sistem Klasemen Series": [
    "P1: 25 poin, P2: 22 poin, hingga P8: 15 poin, dan seterusnya menyesuaikan tiap kelas",
    "Kategori klasemen: Grand Champion, Champion, Pro, Novice, Rookie, Beginner, Amateur, Newbie",
  ],
  "🚦 Aturan Tambahan Perlombaan": [
    "Maks. 8 rider per grup, 8 finalis tiap kelas",
    "Jika poin sama, lihat hasil finish terakhir",
    "Panggilan start 3x. Tidak datang: DNS +8 poin",
    "Tidak menyelesaikan race = DNF +8 poin",
    "Dilarang melakukan jump start. Pelanggaran: +8 poin",
    "Jika ½ rider jatuh sebelum garis merah saat start: race bisa diulang 1x",
    "Dilarang overtake membahayakan (menyudutkan, tabrakan). Pelanggaran: +8 poin",
    "Manuver berbahaya (tabrak disengaja, pengereman mendadak): +8 poin",
    "Dilarang shortcut lintasan. Pelanggaran: +4 poin",
    "Keberatan hanya diterima dengan bukti video yang jelas",
    "Marshall menjaga keamanan, membantu rider jatuh setelah dilewati rider lain",
    "Jika aman, Marshall boleh langsung bantu rider jatuh",
    "Marshall boleh hentikan start jika track dinilai tidak aman",
    "Marshall hanya menyentuh rider dalam kondisi tidak aman/tidak bisa bangun sendiri",
    "Finish bersamaan: ditentukan lewat video (roda depan)",
    "Force majeure: Race Director berhak hentikan race dan musyawarah dengan peserta",
    "Keberatan wajib disampaikan sebelum race selanjutnya dimulai, disertai video",
    "Rider wajib hadir 90 menit sebelum race. Jika race dipercepat dan rider tidak hadir setelah dipanggil 3x: DNS atau +8 poin",
    "Kelas Baby Rider (umur 1–2 tahun): 1 wali boleh masuk track (tanpa sentuhan dan tidak ganggu jalur)",
  ],
};

export default rules;
