const rules = {
	"Regulasi Sepeda": [
		"Sepeda yang digunakan adalah sepeda pushbike/balance bike yang sesuai dengan ukuran roda 12 inch",
		"Panjang handlebar max 48cm dan wajib menggunakan bar end karet / plastik",
		"Wajib menggunakan stem protector demi keamanan rider",
		"Dilarang menambah rem dan lampu yang dapat mengganggu jalannya perlombaan dan membahayakan untuk riders serta peserta lainnya",
	],
	"Regulasi Riders": [
		"Rider wajib menggunakan helm dan tali wajib dikaitkan akan ada penalty poin +5 apabila melanggar ketentuan",
		"Riders wajib menggunakan sepatu dan kaos kaki ketika akan start akan ada penalty poin +5 apabila melanggar ketentuan",
		"Dilarang keras menggunakan ornament lampu atau sejenisnya dihelm sepatu maupun baju/jersey yang dapat mengganggu konsentrasi peserta lain akan ada penalty point +5 jika ketentuan ini dilanggar",
		"Disarankan untuk menggunakan alat keselamatan tambahan seperti sarung tangan knee dan elbow protector",
		"Riders wajib menggunakan number plate yang sudah dibagikan ketika registrasi apabila tidak memakai maka riders dianggap DNS (Did Not Start)",
		"Riders wajib mengikuti kelas sesuai tahun lahir dan gendernya (boy dan girl) atau naik kelas diatasnya. Dilarang keras untuk turun kelas atau melakukan kecurangan data untuk balapan dengan usia dibawahnya yang lebih muda apabila terbukti melanggar maka riders dinyatakan gugur dan dilarang selamanya mengikuti seluruh event pushbike Lampung Academy",
	],
	"Regulasi Wali Riders": [
		"Wali tidak diperkenankan memasuki area track / area steril yang telah ditentukan race director (wali diperkenankan masuk ke track setelah mendapatkan persetujuan race director apabila riders terjatuh dan tidak mau melanjutkan race)",
		"Wali harus berjarak minimal 15 meter dari riders ketika start dan dilarang menyentuh rider apabila terbukti melanggar penalty poin +5",
		"Wali dilarang memasuki area finish yang telah ditentukan apabila melanggar akan ada penalty poin +5",
		"Hanya boleh ada max 2 wali riders dan 1 pelatih setiap tim/komunitas yang diperkenankan membantu ridernya diwaiting zone",
		"Wali rider dilarang menggunakan alat bantu komunikasi / property yang dapat mengganggu konsentrasi riders lain",
		"Wali riders wajib menjaga etika kesopanan keamanan kenyamanan dan kebersihan selama race berlangsung apabila terbukti melanggar maka panitia berhak menegur dan menindak sesuai hukum UU yang berlaku",
	],
	"Regulasi Perlombaan": [
		"Dilarang menambah alat perekam di sepeda helm atau bagian tubuh riders",
		"Apabila rider membawa dokumentasi pribadi dilarang memasuki area track dokumentasi pribadi hanya diperkenankan di luar track dan tidak mengganggu area dokumentasi dari penyelenggara",
		"Race akan dilakukan dengan 6 line gate start.",
		"Perhitungan poin menggunakan sistem poin terendah yang akan melanjutkan ke tahap selanjutnya ~ P1 mendapatkan point 1 ~ P2 mendapatkan point 2 ~ P3 mendapatkan point 3 ~ dst",
		"Untuk kelas yang hanya ada 1 grup akan memainkan 3x moto dengan gate yang berbeda dan juara akan ditentukan dengan menghitung perolehan point yang akan diurutkan dari yang terendah ke yang terbesar apabila ada persamaan poin maka penentuan posisi podium melihat dari posisi finish moto terakhir",
		"Kelas yang terdiri dari 2 grup akan memainkan 2x moto dengan gate yang berbeda peringkat 1-3 setiap grup menuju final utama peringkat 4-6 setiap grup menuju final novice",
		"Kelas yang terdiri dari 3 grup akan memainkan 2x moto dengan gate yang berbeda peringkat 1-4 setiap grup akan menuju babak semifinal pada babak semifinal peringkat 1-3 setiap grup semifinal menuju final utama peringkat 4-6 setiap grup semifinal menuju final novice peringkat 5 - 6 masing - masing batch saat kualifikasi moto akan menjalani final beginner",
		"Kelas yang terdiri dari 4 grup akan memainkan 2x moto dengan gate yang berbeda peringkat 1-3 setiap grup akan menuju babak semifinal pada babak semifinal peringkat 1-3 setiap grup semifinal menuju final utama peringkat 4-6 setiap grup semifinal menuju final novice peringkat 4 - 6 masing - masing batch saat kualifikasi moto akan di pertandingan kembali untuk menentukan final beginner dan amateur peringkat 1 - 3 akan melaju ke final beginner peringkat 4 - 6 menjalani final amateur.",
		"Dalam satu grup maksimal hanya akan berisi 6 riders yang artinya akan ada 6 finalis yang akan memperebutkan podium utama novice beginner dan amateur di setiap kelasnya",
		"Dalam sistem moto jika terjadi poin yang sama maka akan dilihat dari peringkat terbaik ketika finish di moto terakhir untuk menentukan posisi yang lebih baik",
		"Petugas pemanggilan start hanya memanggil sebanyak 3x selanjutnya riders akan dianggap DNS (Did Not Start) apabila tidak segera bersiap di gate start",
		"Riders yang tidak menyelesaikan finish setiap babak maka akan dianggap DNF (Did Not Finish) dan akan diberikan penalty poin +6",
		"Dalam melakukan start seluruh riders dilarang bergerak melompati gate start yang belum benar - benar terbuka apabila gate belum terbuka dan roda terlihat menaiki gate start maka dianggap melakukan jump start dan dikenakan penalty poin +6",
		"Apabila ketika melakukan start dan riders terjatuh minimal ½ dari total jumlah starter sebelum melewati red line (seluruh permukaan gate start) maka start akan diulang maksimal 1x.",
		"Seluruh riders dilarang mengambil overtake yang membahayakan riders lain atau mengakibatkan benturan antar riders (menyudutkan riders lain ke arah batas track sehingga riders lain harus memperlambat laju atau bahkan terjatuh menabrak pembatas track) akan dianggap melakukan pelanggaran apabila melakukan akan penalty point +6",
		"Manuver berbahaya apabila riders kedapatan sengaja menabrak riders didepannya hingga riders didepannya terjatuh di track lurus maupun belokan maka dianggap pelanggaran dan dikenakan penalty poin +6",
		"Seluruh riders dilarang keras menerobos atau melakukan shortcut lintasan yang telah ditentukan apabila terjadi maka penalty poin +4 apabila terbukti melanggar",
		"Race director akan mengambil sikap jika ada keberatan yang diajukan terhadap salah satu riders terkait pelanggaran di poin 13 15 16 17. Pengajuan keberatan wajib menyertakan video yang jelas sebagai bukti. Apabila tidak dapat menyertakan video sebagai bukti makan race director berhak mengambil sikap bahwa race berjalan normal tanpa adanya pelanggaran",
		"Marshall akan bertugas menjaga keamanan track (steril dari pengunjung kebersihan permukaan track dan pembatas yang terpasang baik dan benar) serta membantu riders yang terjatuh setelah seluruh riders lain melewati riders yang terjatuh",
		"Marshall dapat segera membantu riders yang terjatuh apabila di luar racing line atau dinilai aman dan tidak mengganggu riders lain tanpa harus menunggu seluruh riders melewatinya",
		"Marshall berhak menghentikan race ketika start belum dimulai apabila ditemukan hal - hal yang mengganggu keamanan riders ketika di track",
		"Marshall hanya akan menyentuh sepeda anak yang terjatuh dan memastikan sepeda siap digunakan riders marshall baru menyentuh riders apabila riders berada diposisi yang tidak aman atau tidak bisa bangun sendiri (tertimpa sepeda sendiri sepeda riders lain atau tertimpa riders lain yang terjatuh)",
		"Apabila ada riders yang masuk garis finish hampir bersamaan maka akan ditentukan posisi finish melalui rekaman video sebagai bukti dimana roda depan yang terlebih dahulu menyentuh garis finish yang akan dinyatakan sebagai posisi finish yang lebih baik",
		"Setiap kategori race akan diawali kategori gender girl",
		"Apabila terjadi force majeure dalam jalannya race maka race director berhak memberhentikan jalannya race dan melakukan musyawarah dengan perwakilan peserta untuk memutuskan kelanjutan race tersebut",
		"Dalam penyampaian atau mengajukan keberatan terhadap jalannya race wajib disampaikan secara langsung melalui race director disertai video bukti. Proses pengajuan keberatan wajib disampaikan sebelum race selanjutnya berlangsung. Keberatan yang diajukan setelah race selanjutnya berlangsung dianggap gugur.",
		"Setiap rider wajib hadir 90 menit sebelum race dilaksanakan sesuai jadwal yang sudah ditentukan panitia untuk mengantisipasi jadwal mengalami percepatan. Apabila jadwal race mengalami percepatan lebih cepat dalam range 90 menit dari waktu jadwal yang telah ditentukan panitia sebelumnya dan apabila rider tidak ada setelah dipanggil 3x oleh panitia untuk melakukan start maka akan dinyatakan (DNS) Did Not Start atau penalty point +6",
		"Khusus 2022 mix wali rider diperbolehkan masuk track agar anak mau melanjutkan race setelah semua rider melewati tikungan pertama (setelah mendapatkan ijin dari panitia)",
	],
};

export default rules;
