const rules = {
  "🚲 Regulasi Sepeda": [
    "Sepeda yang digunakan adalah pushbike/balance bike roda 12 inch",
    "Panjang handlebar maksimal 48 cm dan wajib memakai bar end karet/plastik",
    "Wajib menggunakan stem protector untuk keamanan rider",
    "Dilarang menambah rem dan lampu yang mengganggu lomba dan membahayakan rider lain",
  ],
  "🧒 Regulasi Riders": [
    "Semua race dibagi berdasarkan kategori tahun lahir",
    "Helm wajib dikenakan dan dikaitkan (Pelanggaran = +3 poin)",
    "Wajib menggunakan sepatu dan kaos kaki saat start (Pelanggaran = +3 poin)",
    "Dilarang menggunakan ornamen lampu di helm, sepatu, atau jersey yang mengganggu (Pelanggaran = +3 poin)",
    "Disarankan memakai alat pelindung tambahan: sarung tangan, knee & elbow protector",
    "Wajib memakai number plate resmi saat registrasi (Jika tidak = DNS)",
    "Wajib ikut kelas sesuai umur atau naik kelas, tidak boleh turun kelas atau manipulasi data (Pelanggaran = diskualifikasi permanen)",
  ],
  "👨‍👩‍👧 Regulasi Wali Riders": [
    "Wali tidak boleh masuk area steril track kecuali diizinkan Race Director saat rider terjatuh (Melanggar = +8 poin)",
    "Wali harus berjarak minimal 1,5 meter dari rider saat start, tidak boleh menyentuh rider (Melanggar = +3 poin)",
    "Wali dilarang masuk area finish (Melanggar = +8 poin)",
    "Maksimum 2 wali + 1 pelatih per tim/komunitas boleh membantu di waiting zone",
    "Dilarang pakai alat komunikasi atau properti yang mengganggu rider lain (Melanggar = +8 poin)",
    "Tidak boleh merokok/vape di luar area yang ditentukan (Melanggar = diskualifikasi)",
    "Wali wajib menjaga etika, kesopanan, keamanan, kenyamanan, kebersihan (Pelanggaran = sanksi panitia, termasuk diskualifikasi)",
  ],
  "🏁 Regulasi Perlombaan": [
    "Tidak boleh pasang alat perekam di sepeda/helm/tubuh rider",
    "Dokumentasi pribadi hanya boleh di luar track dan tidak mengganggu dokumentasi resmi",
    "Start dilakukan dengan 8 gate",
    "Poin menggunakan sistem terendah (P1 = 1, P2 = 2, P3 = 3, dst)",
    "Kelas dengan 1 grup main 3x moto, hasil dari total poin (Podium dilihat dari hasil finish moto terakhir jika poin sama)",
    "Kelas 2 grup main 2x moto: P1-P4 masuk final Grand Champion, P5-P8 masuk final Champion",
    "Untuk event series, klasemen poin berdasarkan kategori dan posisi (P1: 25, P2: 22, ..., P8: 15 per kategori)",
    "1 grup maksimal 8 rider → 8 finalis (Grand Champ, Champion, Pro, dst)",
    "Poin seri sama → diurutkan berdasarkan finish terakhir",
    "Pemanggilan start 3x, jika tidak hadir = DNS dan +8 poin",
    "Tidak menyelesaikan lomba = DNF dan +8 poin",
    "Jump start (roda menyentuh gate sebelum terbuka) = +8 poin",
    "Jika ½ jumlah starter jatuh sebelum garis merah → race diulang 1x",
    "Overtake membahayakan/benturan = +8 poin",
    "Manuver tabrak disengaja = +8 poin",
    "Shortcut lintasan = +4 poin",
    "Protes wajib disertai video, jika tidak = tidak diproses",
    "Marshall menjaga keamanan & bantu rider setelah aman",
    "Marshall boleh bantu rider jatuh jika aman",
    "Marshall bisa hentikan race jika tidak aman",
    "Marshall hanya boleh sentuh rider jika dalam bahaya",
    "Finish bersamaan → ditentukan dengan video bukti roda depan",
    "Force majeure → race bisa dihentikan & dimusyawarahkan",
    "Protes harus sebelum race selanjutnya, setelah itu gugur",
    "Rider wajib hadir 90 menit sebelum jadwal race (Jika race dipercepat dan rider tidak ada setelah dipanggil 3x = DNS atau +8 poin)",
    "Kelas baby rider (1-2 tahun): wali boleh masuk track hanya untuk mendampingi (tanpa menyentuh atau ganggu jalur lain), dengan izin Race Director",
  ],
};

export default rules;
