const sponsor = [
  "ITERA",
  "Krakatau Festival",
  "Lampung Boemi Event",
  "Honda Intimobil",
  "Wong Coco",
  "Star & Hero",
  "Delbis",
  "Rosa Hostel",
  "Rio By The Beach",
  "Petal Of Joy",
  "Relaxa",
  "Air Alam",
  "Kancang Run Bike",
  "Lapak Pushbike",
  "Papapit",
  "4Hostel",
  "ASDP",
  "Kopi Jejamo",
  "Salsa Colection",
  "Shaka Garage",
  "Laundry Pro",
  "Sogood",
  "Rayyan",
  "Tunas Honda",
  "Beeme",
  "Abang Ibra",
  "The Santoso",
  "Big Boss",
  "Keenan",
  "CEDEA",
  "Agib",
  "Risol Mamayo",
  "Rebel Of Justice",
  "Wings Food",
  "Hydrococo",
  "Sunpride",
  "Inaco",
  "Prodia",
  "Remblong",
  "Grand",
  "Onekidz",
  "Hexton Hotel",
  "Black Fit",
  "Iron Fit Gym",
  "Kaukaustore",
];

export default sponsor;
